### ISSUE TITLE
Logout Confirmation Notification

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#10]
When reviewing the system, I noticed that users are not informed about the confirmation of their logout. To enhance user experience, I request the addition of a feature that displays a message when a user logs out, ensuring they are notified of the successful logout.

**Comment by SamirShresthaa** [comment]
![Screenshot 2024-04-21 225738](https://github.com/Tenzing07/One-Byte-Food/assets/119719500/a91d6dc5-21df-47e6-ab28-436edda9a27d)
I have added the feature that displays a message when a user logs out, ensuring they are notified of the successful logout.
