### ISSUE TITLE
Bug 1: Inaccessible Menu Page via Navigation Bar

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#13]
![Screenshot 2024-05-08 181118](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/64bf07a9-523e-4210-8ce9-2b0600f5a0f9)
The menu page isn't accessible through the navigation bar as intended. Instead, I have to manually modify the URL to access it. This inconvenience disrupts the user experience and navigation flow. Could you please investigate this issue thoroughly and ensure that the menu page is accessible through the navigation bar as expected? Your prompt attention to fixing this bug would be greatly appreciated.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by bristinaprajapati** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/e44350e6-9db5-4061-a9bc-a3e5d9514ff0)
I have investigated the bug and solved the issue. The user can now successfully access menu page through navigation bar.
