### ISSUE TITLE
Bug 2: Issue with Displaying Images on Menu Items Click

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#16]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/c8f4ea1f-c494-4d22-836c-cf8b8d940d0c)
When clicking on menu items, the images linked to some of the items are not loading or displaying correctly upon clicking, affecting the visual presentation and user experience. . I kindly ask that you thoroughly investigate this issue to identify the underlying cause and implement a solution as quickly as possible to restore full functionality to the menu page.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by bristinaprajapati** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/be25a67e-1a26-45c7-844c-56c7a2e2b728)
I have investigated the bug and solved the issue. Now when clicking on menu items, the images of the items are displaying correctly
