### ISSUE TITLE
Bug 3: : Non-Functional Login and Sign-Up Buttons on Non-Homepage Pages

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#17]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/bf835374-dda0-49e8-bae4-f100b2951e47)
When navigating to a page other than the homepage, the login and sign-up buttons do not function. Despite being displayed as clickable elements, the login and sign-up buttons fail to perform any action on non-homepage pages, leading to a lack of functionality and usability. 
Additionally, the login and sign-up buttons appear too cluttered together, impacting the visual appeal and usability of the interface.
Can you thoroughly investigate the cause of this bug and implement fixes as soon as possible to ensure that the login and sign-up buttons function properly on all pages.

**Comment by bristinaprajapati** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/d97231be-aa0a-4001-bb2f-6f347acf7f71)
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/7c68c555-26dc-426d-9dc8-f7a7c17a01ec)
I have successfully investigated the bug and solved the issue. Now login and sigh up button is functional from every page of the website. I have also managed the visual appearance of the login and sign up buttons.
