### ISSUE TITLE
Bug 4: Inactive Navigation Tab Highlighting

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#18]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/91c90dd8-dc7a-4be8-83a0-f1c79e1f45d0)
Despite navigating to different sections within the application, the corresponding navigation tab does not visually indicate the user's current location or active tab, leading to confusion and usability issues. Can you investigate through this bug and implement a fix to it as soon as possible.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by bristinaprajapati** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/527c7b51-db6f-4150-8f0d-87a0a6734201)
I have investigated the bug and solved the issue. Now the navigation tab visually indicate the user's current location or active tab.

**Comment by bristinaprajapati** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/6072dfe6-de71-457d-a33e-8386145f5174)
I have investigated the bug and solved the issue. Now the navigation tab visually indicate the user's current location or the active tab.
