### ISSUE TITLE
Bug 5: Malfunctioning Check Booking Availability Filter in Tables Section

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#19]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/5c7c1a3e-1acd-49d2-bd03-f847c5d67e52)
When reviewing through the system, I noticed that despite being designed to filter and sort the tables accordingly, the table filter fails to display accurate results. Can you investigate this bug thoroughly and implement a fix as soon as possible to ensure that the filter in the tables section functions properly, allowing users to  filter the tables accurately and efficiently.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by AvimanShahi** [comment]
I have added the filter system in the tables.php where a user can filter the table base on the booking data, time and the max number of people 
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/f3862ad0-3b03-4b32-97fc-8ad110176178)
Here you can see the feature has displayed the table which have more then ten number of people can user can book them
