### ISSUE TITLE
Bug 6: Inoperative Booking Histories Feature in the User Profile

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#20]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/4b2fa524-808e-435f-84ff-6ede3a130168)
When in reviewing the profile section of the user, I noticed that the 'Booking History' section remaining empty despite having reserved a number of tables. This type of bug renders the whole feature non-functional. Can you review through your codes and figure out what the problem and fix this bug accordingly.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by AvimanShahi** [comment]
I have added booking history to the user profile where when the user book any table it will show it here
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/53ad3bae-959f-4d9f-91c3-782ca76b8d0b)
