### ISSUE TITLE
Bug 7: Non-Functional "More Tables" Button on Home Page

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#21]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/8128cc11-70ea-460a-b17d-c9d7db5be123)
Despite being displayed as a clickable button, the "More Tables" button available beneath the 'Our Tables' section in the Home page , it does not perform any action as expected, leading to a lack of functionality and usability.
Can you investigate this problem and fix it so that when in clicking on the "More Tables" button will direct the user to the tables page where they can review more tables offered by the restaurant.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by AvimanShahi** [comment]
When the button is is click it will redirect to the tables.php where all the tables are fetched
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/d3b85a3f-bdb2-417f-9cb3-ccf845157bd5)
