### ISSUE TITLE
Bug 8: The Images not Displaying in "Our Tables" Section

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#22]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/77e82867-080c-4b0a-a08d-fa2f03919768)
The 'Our Tables' section is designed to display images of tables, but there seems to be  malfunction in fetching and displaying these images on the user-side, even though they are correctly stored and accessible from the database and the admin-side. Kindly, investigate through this bug and implement a proper solution to it.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by AvimanShahi** [comment]
I have successfully fetched the images in the tables and fix the issue
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/1e6e7f19-f6c5-44e0-877c-fb39747c7fb4)
