### ISSUE TITLE
Bug 13: Problem with Redirecting from Reviews Card in Admin Panel Dashboard

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#27]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/be698743-657c-4fab-8ef7-50d9afc10aa2)
Despite being designed as a clickable element, the reviews  card fails to redirect the admin to the user page as expected, leading to a lack of functionality and usability in the dashboard section. Thoroughly investigate the problem and implement a fix as soon as possible to ensure that clicking on the reviews card in the admin panel dashboard redirects the admin to the reviews page as intended, enhancing navigation and usability for administrators.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by Tenzing07** [comment]
I’ve addressed the issue you reported with the reviews card in the admin panel. I’ve updated the functionality to ensure that clicking on the reviews card now correctly redirects the admin to the reviews page as intended. This change should improve navigation and usability in the dashboard section. Please refresh your admin panel to see the changes. If you encounter any more issues or need further adjustments, feel free to let me know.
