### ISSUE TITLE
Bug 14: The Total Tables Card Not Updating Correctly in Admin Dashboard

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#28]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/116e9db4-f825-439d-8956-bc28f1046b55)
The total reservation card in the admin dashboard is not being updated as expected. Despite having performed changes in the database and the system regarding table reservation counts, the total reservation card on the admin dashboard fails to reflect the updated number accurately. This discrepancy leads to an incorrect representation of the current total reservation count. 
Kindly, investigate the bug thoroughly and implement a fix as soon as possible to ensure that the total reservation card in the admin dashboard updates correctly and reflects the actual number of reservations in the system, maintaining data accuracy and reliability.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by Tenzing07** [comment]
I’ve addressed the issue you reported with the total reservation card in the admin dashboard. I’ve investigated the problem and implemented a fix to ensure that the total reservation card now correctly updates and reflects the actual number of reservations in the system. This change should improve data accuracy and reliability. Please refresh your admin panel to see the changes. If you encounter any more issues or need further adjustments, feel free to let me know. Thank you for bringing this to my attention!
