### ISSUE TITLE
Bug 15: Update Label for "Mark as Read" Option in Admin Reviews Page

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#29]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/5ca29a2d-bead-4b93-927c-edaa9896559e)
The reviews page of the admin-side panel, indicates a feature allowing the admin to mark the reviews as read to ensure that the reviews are managed properly, but the option to 'mark as read' should be changed to 'mark all as read' for a improved clarity and functionality. Currently, the wording "Mark as Read" implies that it only applies to individual reviews, whereas the intended functionality is to mark all reviews as read.
Kindly, investigate this problem and update the label for the 'mark as read' option in the admin reviews page to 'mark all as read' for improved clarity and functionality.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by Tenzing07** [comment]
I’ve taken your feedback into account and have updated the label for the ‘mark as read’ option in the admin reviews page to ‘mark all as read’. This change should improve clarity and accurately reflect the functionality of marking all reviews as read. Please refresh your admin panel to see the changes. If you have any more suggestions or find any other issues, feel free to let me know. Thank you for your valuable feedback!
