### ISSUE TITLE
Database Naming and Consistency

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#3]
After reviewing the database tables, I recommend paying close attention to the naming conventions for both database tables and columns to ensure ease of future access. It's crucial to ensure that data is stored securely and properly to mitigate any potential data loss risks. I trust that you will take the necessary steps to safeguard the integrity and accessibility of the stored data.
Also add the database table for the admin separately as it it required for this sprint. 

![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/dc1af8ad-1b96-4223-9c97-58d116bd81ac)

**Comment by AvimanShahi** [comment]
Yes i have added the admin panel i have looked into the naming convention and now the issue is solved.

**Comment by AvimanShahi** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/64d0998a-8b12-465b-8467-bec56f75e0ce)
