### ISSUE TITLE
Bug 16: Non-Functional Delete Reviews Action in Admin-Side Panel 

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#30]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/2fb43329-ab85-4287-a521-2252c52c4564)
The action to delete reviews on the reviews page of the admin-side panel appears to be non-functional. Despite having a designated option to delete reviews, the functionality fails to execute the deletion action, leading to a lack of review management capability for admin. 
Kindly, investigate this problem thoroughly and implement a fix as soon as possible to ensure that the delete reviews action in the admin-side panel functions properly.

**Comment by prinsha13** [comment]
For further clarification regarding this issue please review the bug report.

**Comment by Tenzing07** [comment]
I’ve addressed the issue you reported with the delete reviews functionality in the admin panel. I’ve investigated the problem and implemented a fix to ensure that the delete reviews action now functions properly. This change should improve review management capability for admins. Please refresh your admin panel to see the changes.
