### ISSUE TITLE
Issue with Non-functional link tabs in the footer section 

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#31]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/5f2627db-2219-4784-9bc4-05002668d323)
Upon thorough review of the system application, I observed that the links within the footer section are presently not functioning as intended. To enhance user experience and ensure seamless navigation, I recommend implementing a functionality that enables clicking on a tab to directly lead the user to the corresponding page or section. This enhancement would greatly improve the overall usability and accessibility of the system.

**Comment by bristinaprajapati** [comment]
I have investigated the issue and solved it. The links in the footer now directs to each intended pages when clicked.
