### ISSUE TITLE
Booking History: Inoperative Cancellation Feature in Profile Page

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#32]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/fcde6cec-1585-4b11-963b-fe600114c12a)
It has come to my attention that the cancellation feature within the booking histories section of the profile page is not functioning as intended. Kindly, investigate this issue thoroughly and implement the solution to it as soon as possible.

**Comment by AvimanShahi** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/ae971b03-e130-4931-be97-cf74802bcdf7)
I have successfully added the  booking cancelation feature where a user can cancel the booking he/she had made.
