### ISSUE TITLE
Unnecessary Edit functionality in the user details section 

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#33]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/f2f7bb5e-b2c0-4ff5-9ca8-b846b5cd2413)
When reviewing the system application, I noticed that you have added an ‘Edit’ button featuring a functionality that allows the admin to edit the user details. The edit functionality in user details for administrators is unnecessary and may pose a risk of breaching personal information. Kindly, investigate this matter and ensure that the edit feature in the user page is removed.

**Comment by Tenzing07** [comment]
I’ve taken your feedback into account and have removed the ‘Edit’ button from the user details section in the admin panel. This change is in line with our commitment to uphold user privacy and security. The administrators will no longer be able to edit user details directly from the admin panel. Please refresh your admin panel to see the changes. If you have any more suggestions or find any other issues, feel free to let me know. Thank you for your valuable feedback!
