### ISSUE TITLE
Issue: Inconsistent Email and Social Media links in the "Reach Us" and "Contact Us" Section.

### ISSUE THREAD

**Issue by deleenananaa** [Tenzing07/One-Byte-Food#35]
The social media links in both the home page and contact us page, redirects into the page itself. Additionally, the email of the restaurant should also be changed to the restaurant's email address: onebytefoods@gmail.com
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119421004/eb0f68d2-dddf-4fad-b5ac-cfab6b3aff2e)
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119421004/6fce1441-c1e3-4d2c-9907-626d85f1a20a)

**Comment by bristinaprajapati** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/eff37cc8-8091-4f3a-859a-17678e8da564)
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119391321/a48e2863-9a02-4dc2-a0d0-4d0a6081f208)
I have resolved the issue and now  social media links in both the home page and contact us page, redirects into the desired pages and the email is also changed.
