### ISSUE TITLE
Issue: "Book Now" Button Failing to Redirect

### ISSUE THREAD

**Issue by deleenananaa** [Tenzing07/One-Byte-Food#36]
After clicking the "Book Now" button, the page should be redirected to Tables Section of the website, enabling users to book and reserve their tables. 
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119421004/56d4d71c-ed55-4e41-aba9-860eeb74e6e4)
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119421004/16d93824-78df-45aa-b67a-e411721bea87)

**Comment by AvimanShahi** [comment]
i have solved the issue

**Comment by AvimanShahi** [comment]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/8774a35d-ecc6-4220-9117-35ab8c4ace01)
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119503363/d4c08c91-787c-4380-a63d-6b2830afb5e2)
Now when i clicked book now it redirect to the tabel.php where a user can book the table
