### ISSUE TITLE
Issue: User Table in Admin Panel Displayed Too Small

### ISSUE THREAD

**Issue by deleenananaa** [Tenzing07/One-Byte-Food#37]
The users table in admin panel is too small. The action buttons are also constricted. Please make sure that the table fits in the blank space of the entire User Section.
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119421004/e1441717-d1fa-4891-abc1-93197ec613b1)

**Comment by Tenzing07** [comment]
I’ve addressed the issue you reported with the users table in the admin panel. I’ve adjusted the CSS to ensure that the table and action buttons are appropriately sized and fit within the User Section. The table should now utilize the available space more effectively, providing a better user experience. Please refresh your admin panel to see the changes. If you encounter any more issues or need further adjustments, feel free to let me know! Thank you

**Comment by Tenzing07** [comment]
I’ve addressed the issue you reported with the users table in the admin panel. I’ve adjusted the CSS to ensure that the table and action buttons are appropriately sized and fit within the User Section. The table should now utilize the available space more effectively, providing a better user experience. Please refresh your admin panel to see the changes. If you encounter any more issues or need further adjustments, feel free to let me know! Thank you
