### ISSUE TITLE
Admin Dashboard(Customer Queries)

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#4]
After assessing the admin dashboard's side panel, I noticed that the page for customer queries is missing. I strongly recommend adding this page, as it plays a vital role in facilitating customer engagement, which is crucial for the success of the project.
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/a9a97cd2-a40e-49b0-a87c-efc3ecd00b64)

**Comment by Tenzing07** [comment]
i have added the customer queries page in the admin panel if any other issue arised let me know
