### ISSUE TITLE
Menu(Add pictures for enhancing customer experience)

### ISSUE THREAD

**Issue by prinsha13** [Tenzing07/One-Byte-Food#5]
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119413427/40f83cb6-314b-4869-86fa-8f9f17c6e804)
After reviewing the menu section,  I think it would enhance the customer experience to include pictures alongside the menu items. This visual representation will provide customers with a clearer overview of the dishes they are considering, making the menu more appealing and user-friendly.

**Comment by bristinaprajapati** [comment]
I have updated the menu section so that now when a user clicks on a food item, a pop-up appears which displays the picture and price of the dish for more clearer and more engaging experience.
