### ISSUE TITLE
Removal of unnecessary button "More Details" in the system 

### ISSUE THREAD

**Issue by deleenananaa** [Tenzing07/One-Byte-Food#9]
According to the project requirements and backlog, providing additional details about the table was suggested, which would potentially result in content redundancy. Therefore, we concluded that it was unnecessary and opted to remove it. Please address the bug indicated in the following screenshot:
![image](https://github.com/Tenzing07/One-Byte-Food/assets/119421004/cbed4c68-cad6-4a97-bf1d-524440564361)

**Comment by bristinaprajapati** [comment]
I have addressed the issue and have removed the button as discussed.
